import type { AchievementDef, AchievementCheckStats } from "@/src/domain/entities/achievement";

export type { AchievementDef, AchievementCheckStats } from "@/src/domain/entities/achievement";

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: "first_step",
    icon: "shoe-sneaker",
    title: "ПЕРВЫЙ ШАГ",
    description: "Сделайте первые 100 шагов",
    category: "steps",
    condition: (s) => s.totalSteps >= 100,
    progress: (s) => ({ current: Math.min(s.totalSteps, 100), total: 100 }),
  },
  {
    id: "walk",
    icon: "walk",
    title: "ПРОГУЛКА",
    description: "Пройдите 1 000 шагов за день",
    category: "steps",
    condition: (s) => s.currentDaySteps >= 1000,
    progress: (s) => ({ current: Math.min(s.currentDaySteps, 1000), total: 1000 }),
  },
  {
    id: "active_day",
    icon: "run",
    title: "АКТИВНЫЙ ДЕНЬ",
    description: "Пройдите 5 000 шагов за день",
    category: "steps",
    condition: (s) => s.currentDaySteps >= 5000,
    progress: (s) => ({ current: Math.min(s.currentDaySteps, 5000), total: 5000 }),
  },
  {
    id: "champion",
    icon: "trophy",
    title: "ЧЕМПИОН",
    description: "Пройдите 10 000 шагов за день",
    category: "steps",
    condition: (s) => s.currentDaySteps >= 10000,
    progress: (s) => ({ current: Math.min(s.currentDaySteps, 10000), total: 10000 }),
  },
  {
    id: "marathoner",
    icon: "map-marker-distance",
    title: "МАРАФОНЕЦ",
    description: "Пройдите 100 000 шагов всего",
    category: "steps",
    condition: (s) => s.totalSteps >= 100000,
    progress: (s) => ({ current: Math.min(s.totalSteps, 100000), total: 100000 }),
  },
  {
    id: "ultra",
    icon: "star",
    title: "УЛЬТРА",
    description: "Пройдите 1 000 000 шагов всего",
    category: "steps",
    condition: (s) => s.totalSteps >= 1000000,
    progress: (s) => ({ current: Math.min(s.totalSteps, 1000000), total: 1000000 }),
  },
  {
    id: "burner",
    icon: "fire",
    title: "СЖИГАТЕЛЬ",
    description: "Сожгите 500 ккал за день",
    category: "calories",
    condition: (s) => s.currentDayCalories >= 500,
    progress: (s) => ({ current: Math.min(s.currentDayCalories, 500), total: 500 }),
  },
  {
    id: "energy",
    icon: "lightning-bolt",
    title: "ЭНЕРГИЯ",
    description: "Сожгите 1 000 ккал за день",
    category: "calories",
    condition: (s) => s.currentDayCalories >= 1000,
    progress: (s) => ({ current: Math.min(s.currentDayCalories, 1000), total: 1000 }),
  },
  {
    id: "calorie_killer",
    icon: "skull",
    title: "КАЛОРИ-КИЛЛЕР",
    description: "Сожгите 10 000 ккал всего",
    category: "calories",
    condition: (s) => s.totalCalories >= 10000,
    progress: (s) => ({ current: Math.min(s.totalCalories, 10000), total: 10000 }),
  },
  {
    id: "furnace",
    icon: "weather-fire",
    title: "ТОПКА",
    description: "Сожгите 100 000 ккал всего",
    category: "calories",
    condition: (s) => s.totalCalories >= 100000,
    progress: (s) => ({ current: Math.min(s.totalCalories, 100000), total: 100000 }),
  },
  {
    id: "streak_3",
    icon: "counter",
    title: "3 ДНЯ ПОДРЯД",
    description: "Занимайтесь 3 дня подряд",
    category: "streak",
    condition: (s) => s.streakDays >= 3,
    progress: (s) => ({ current: Math.min(s.streakDays, 3), total: 3 }),
  },
  {
    id: "streak_7",
    icon: "calendar-check",
    title: "НЕДЕЛЯ",
    description: "Занимайтесь 7 дней подряд",
    category: "streak",
    condition: (s) => s.streakDays >= 7,
    progress: (s) => ({ current: Math.min(s.streakDays, 7), total: 7 }),
  },
  {
    id: "streak_30",
    icon: "calendar-star",
    title: "МЕСЯЦ",
    description: "Занимайтесь 30 дней подряд",
    category: "streak",
    condition: (s) => s.streakDays >= 30,
    progress: (s) => ({ current: Math.min(s.streakDays, 30), total: 30 }),
  },
  {
    id: "first_challenge",
    icon: "flag-checkered",
    title: "ПЕРВЫЙ ВЫЗОВ",
    description: "Участвуйте в первом челлендже",
    category: "challenge",
    condition: (s) => s.challengesParticipated >= 1,
    progress: (s) => ({ current: Math.min(s.challengesParticipated, 1), total: 1 }),
  },
  {
    id: "challenger",
    icon: "trophy-award",
    title: "ПОБЕДИТЕЛЬ",
    description: "Выиграйте челлендж",
    category: "challenge",
    condition: (s) => s.challengesWon >= 1,
    progress: (s) => ({ current: Math.min(s.challengesWon, 1), total: 1 }),
  },
  {
    id: "champion_5",
    icon: "crown",
    title: "5 ПОБЕД",
    description: "Выиграйте 5 челленджей",
    category: "challenge",
    condition: (s) => s.challengesWon >= 5,
    progress: (s) => ({ current: Math.min(s.challengesWon, 5), total: 5 }),
  },
  {
    id: "social_first",
    icon: "account-plus",
    title: "ДРУЗЬЯ",
    description: "Добавьте первого друга",
    category: "social",
    condition: (s) => s.friendsCount >= 1,
    progress: (s) => ({ current: Math.min(s.friendsCount, 1), total: 1 }),
  },
  {
    id: "social_5",
    icon: "account-group",
    title: "КОМПАНИЯ",
    description: "Добавьте 5 друзей",
    category: "social",
    condition: (s) => s.friendsCount >= 5,
    progress: (s) => ({ current: Math.min(s.friendsCount, 5), total: 5 }),
  },
  {
    id: "distance_10km",
    icon: "map-marker-distance",
    title: "10 КМ",
    description: "Пройдите 10 км всего",
    category: "distance",
    condition: (s) => s.totalDistanceMeters >= 10000,
    progress: (s) => ({ current: Math.min(s.totalDistanceMeters, 10000), total: 10000 }),
  },
  {
    id: "distance_100km",
    icon: "earth",
    title: "100 КМ",
    description: "Пройдите 100 км всего",
    category: "distance",
    condition: (s) => s.totalDistanceMeters >= 100000,
    progress: (s) => ({ current: Math.min(s.totalDistanceMeters, 100000), total: 100000 }),
  },
];

export function checkAchievements(
  achievements: AchievementDef[],
  stats: AchievementCheckStats,
): AchievementDef[] {
  return achievements.filter((a) => a.condition(stats));
}
